/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../modules/transfer-http/transfer-http.module';
import * as import2 from '../../../../modules/transfer-http/transfer-http';
import * as import3 from '@angular/http';
import * as import4 from '../../../../modules/transfer-state/transfer-state';
class TransferHttpModuleInjector extends import0.ɵNgModuleInjector<import1.TransferHttpModule> {
  _TransferHttpModule_0:import1.TransferHttpModule;
  __TransferHttp_1:import2.TransferHttp;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _TransferHttp_1():import2.TransferHttp {
    if ((this.__TransferHttp_1 == null)) { (this.__TransferHttp_1 = new import2.TransferHttp(this.parent.get(import3.Http),this.parent.get(import4.TransferState))); }
    return this.__TransferHttp_1;
  }
  createInternal():import1.TransferHttpModule {
    this._TransferHttpModule_0 = new import1.TransferHttpModule();
    return this._TransferHttpModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.TransferHttpModule)) { return this._TransferHttpModule_0; }
    if ((token === import2.TransferHttp)) { return this._TransferHttp_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TransferHttpModuleNgFactory:import0.NgModuleFactory<import1.TransferHttpModule> = new import0.NgModuleFactory<any>(TransferHttpModuleInjector,import1.TransferHttpModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9uZ3UtZGVtby9zcmMvbW9kdWxlcy90cmFuc2Zlci1odHRwL3RyYW5zZmVyLWh0dHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3Qvbmd1LWRlbW8vc3JjL21vZHVsZXMvdHJhbnNmZXItaHR0cC90cmFuc2Zlci1odHRwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
