/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/globals/globals.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../../app/materials-bclight/mdb-nav/mdb-nav.module';
import * as import4 from '../../../../app/materials-bclight/mdb-button/mdb-button.module';
import * as import5 from '../../../../app/materials-bclight/mdb-sidenav/mdb-sidenav.module';
import * as import6 from '../../../../app/materials-bclight/materials-bclight.module';
class GlobalsModuleInjector extends import0.ɵNgModuleInjector<import1.GlobalsModule> {
  _CommonModule_0:import2.CommonModule;
  _MdbNavModule_1:import3.MdbNavModule;
  _MdbButtonModule_2:import4.MdbButtonModule;
  _MdbSidenavModule_3:import5.MdbSidenavModule;
  _MaterialsBclightModule_4:import6.MaterialsBclightModule;
  _GlobalsModule_5:import1.GlobalsModule;
  __NgLocalization_6:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_6():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  createInternal():import1.GlobalsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._MdbNavModule_1 = new import3.MdbNavModule();
    this._MdbButtonModule_2 = new import4.MdbButtonModule();
    this._MdbSidenavModule_3 = new import5.MdbSidenavModule();
    this._MaterialsBclightModule_4 = new import6.MaterialsBclightModule();
    this._GlobalsModule_5 = new import1.GlobalsModule();
    return this._GlobalsModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.MdbNavModule)) { return this._MdbNavModule_1; }
    if ((token === import4.MdbButtonModule)) { return this._MdbButtonModule_2; }
    if ((token === import5.MdbSidenavModule)) { return this._MdbSidenavModule_3; }
    if ((token === import6.MaterialsBclightModule)) { return this._MaterialsBclightModule_4; }
    if ((token === import1.GlobalsModule)) { return this._GlobalsModule_5; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GlobalsModuleNgFactory:import0.NgModuleFactory<import1.GlobalsModule> = new import0.NgModuleFactory<any>(GlobalsModuleInjector,import1.GlobalsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9nbG9iYWxzL2dsb2JhbHMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvZ2xvYmFscy9nbG9iYWxzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
