/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './factory-card.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../app/main/factory-card/factory-card.component';
const styles_FactoryCardComponent:any[] = [import0.styles];
export const RenderType_FactoryCardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_FactoryCardComponent,
  data: {}
}
);
export function View_FactoryCardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  factory-card works!\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_FactoryCardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-factory-card',([] as any[]),(null as any),(null as any),(null as any),View_FactoryCardComponent_0,RenderType_FactoryCardComponent)),
    import1.ɵdid(57344,(null as any),0,import2.FactoryCardComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const FactoryCardComponentNgFactory:import1.ComponentFactory<import2.FactoryCardComponent> = import1.ɵccf('app-factory-card',import2.FactoryCardComponent,View_FactoryCardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL2ZhY3RvcnktY2FyZC9mYWN0b3J5LWNhcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWFpbi9mYWN0b3J5LWNhcmQvZmFjdG9yeS1jYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWFpbi9mYWN0b3J5LWNhcmQvZmFjdG9yeS1jYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL2ZhY3RvcnktY2FyZC9mYWN0b3J5LWNhcmQuY29tcG9uZW50LnRzLkZhY3RvcnlDYXJkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGZhY3RvcnktY2FyZCB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtZmFjdG9yeS1jYXJkPjwvYXBwLWZhY3RvcnktY2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUc7SUFFQzs7Ozs7O0lDRko7Z0JBQUE7OztJQUFBOzs7In0=
