/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['.mdb-sidenav[_ngcontent-%COMP%] {\n  position:fixed; width:100vw; height:100vh;display:none;left:0; z-index: 999;\n  .sidenav-content {\n    transform: translateX(-100%);height:100vh;background-color:#fff;z-index: 2;width: 250px;position: absolute;\n  }\n  .sidenav-close {\n    background: rgba(0,0,0,.5);opacity:0;height:100vh;width:100vw;position:absolute;left:0;top:0; z-index:1;\n  }\n}'];
