/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.mdb-sidenav[_ngcontent-%COMP%] {\n  position:fixed; width:100vw; height:100vh;display:none;left:0; z-index: 999;\n  .sidenav-content {\n    transform: translateX(-100%);height:100vh;background-color:#fff;z-index: 2;width: 250px;position: absolute;\n  }\n  .sidenav-close {\n    background: rgba(0,0,0,.5);opacity:0;height:100vh;width:100vw;position:absolute;left:0;top:0; z-index:1;\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItc2lkZW5hdi9tZGItc2lkZW5hdi5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2FuZ3VsYXI0LXNzci9zcmMvYXBwL21hdGVyaWFscy1iY2xpZ2h0L21kYi1zaWRlbmF2L21kYi1zaWRlbmF2LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
