/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './news-anonce.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../app/main/news-anonce/news-anonce.component';
const styles_NewsAnonceComponent:any[] = [import0.styles];
export const RenderType_NewsAnonceComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_NewsAnonceComponent,
  data: {}
}
);
export function View_NewsAnonceComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'card blue-grey darken-1'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),7,'div',[[
        'class',
        'card-content white-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Card Title'])),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['I am a very simple card. I am good at containing small bits of information.\n      I am convenient because I require little markup to use effectively.'])),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),7,'div',[[
        'class',
        'card-action'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        '#'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['This is a link'])),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        '#'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['This is a link'])),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_NewsAnonceComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-news-anonce',([] as any[]),(null as any),(null as any),(null as any),View_NewsAnonceComponent_0,RenderType_NewsAnonceComponent)),
    import1.ɵdid(57344,(null as any),0,import2.NewsAnonceComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const NewsAnonceComponentNgFactory:import1.ComponentFactory<import2.NewsAnonceComponent> = import1.ɵccf('app-news-anonce',import2.NewsAnonceComponent,View_NewsAnonceComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL25ld3MtYW5vbmNlL25ld3MtYW5vbmNlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2FuZ3VsYXI0LXNzci9zcmMvYXBwL21haW4vbmV3cy1hbm9uY2UvbmV3cy1hbm9uY2UuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL25ld3MtYW5vbmNlL25ld3MtYW5vbmNlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL25ld3MtYW5vbmNlL25ld3MtYW5vbmNlLmNvbXBvbmVudC50cy5OZXdzQW5vbmNlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNhcmQgYmx1ZS1ncmV5IGRhcmtlbi0xXCI+XG4gIDxkaXYgY2xhc3M9XCJjYXJkLWNvbnRlbnQgd2hpdGUtdGV4dFwiPlxuICAgIDxzcGFuIGNsYXNzPVwiY2FyZC10aXRsZVwiPkNhcmQgVGl0bGU8L3NwYW4+XG4gICAgPHA+SSBhbSBhIHZlcnkgc2ltcGxlIGNhcmQuIEkgYW0gZ29vZCBhdCBjb250YWluaW5nIHNtYWxsIGJpdHMgb2YgaW5mb3JtYXRpb24uXG4gICAgICBJIGFtIGNvbnZlbmllbnQgYmVjYXVzZSBJIHJlcXVpcmUgbGl0dGxlIG1hcmt1cCB0byB1c2UgZWZmZWN0aXZlbHkuPC9wPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImNhcmQtYWN0aW9uXCI+XG4gICAgPGEgaHJlZj1cIiNcIj5UaGlzIGlzIGEgbGluazwvYT5cbiAgICA8YSBocmVmPVwiI1wiPlRoaXMgaXMgYSBsaW5rPC9hPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGFwcC1uZXdzLWFub25jZT48L2FwcC1uZXdzLWFub25jZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0FBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBcUM7TUFDbkM7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFxQztNQUNuQztRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXlCO0lBQWlCO0lBQzFDO0lBQUc7SUFDc0U7SUFDckU7TUFDTjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXlCO01BQ3ZCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBWTtJQUFrQjtNQUM5QjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQVk7SUFBa0I7SUFDMUI7SUFDRjs7Ozs7O0lDVk47Z0JBQUE7OztJQUFBOzs7In0=
