/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['[_nghost-%COMP%]     {\n  #news_items {\n    .header-section {\n      background:url(\'/src/assets/img/bg-news.jpg\') center #69a437 no-repeat\n    }\n    //padding-bottom:0;\n  }\n  #sales_items {\n    .header-section {\n      background:url(\'/src/assets/img/bg-sales.jpg\') center #94434a no-repeat\n    }\n  }\n  #recommend_items {\n    .header-section {\n      background:url(\'/src/assets/img/bg-recommend.jpg\') center #3b9fc3 no-repeat\n    }\n  }\n  #factories_items {\n    .header-section {\n      background:url(\'/src/assets/img/bg-factories.jpg\') center #e26201 no-repeat\n    }\n  }\n  #news_items, #sales_items, #recommend_items, #factories_items {\n    .header-section {\n      height:150px;\n      h2 {font-size: 3rem}\n    }\n    padding-bottom:0;\n  }\n  .header-section {\n    h3 { font-size:1.3rem; margin-top:10px }\n    .relative { height:80px }\n    &__more {\n      position:absolute; left:100%; height:80px; width:80px; top:50%; transform:translate(-50%, -50%); padding:5px;\n      svg { width:100%; height:100%; }\n    }\n  }\n  @media (max-width: 1250px) {\n    #news_items, #sales_items, #recommend_items, #factories_items {\n      .header-section {\n        h2 { font-size:2.5rem;}\n      }\n    }\n  }\n  @media (max-width: 959px) {\n    #news_items, #sales_items, #recommend_items, #factories_items {\n      .header-section {\n        h2 { font-size:2rem; }\n        &__more { left:auto; right:.75rem; transform:translateY(-50%); }\n      }\n    }\n  }\n  .items {transform: translateY(-36px)}\n}'];
