/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['.bg-cell[_ngcontent-%COMP%] { background:url(\'/src/assets/img/bg_cell.jpg\') repeat; overflow:hidden; }\n[_nghost-%COMP%]     h1 { font-size:2rem; }'];
