/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './mdb-nav.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../app/materials-bclight/mdb-nav/mdb-nav.component';
const styles_MdbNavComponent:any[] = [import0.styles];
export const RenderType_MdbNavComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MdbNavComponent,
  data: {}
}
);
export function View_MdbNavComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),3,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    import1.ɵncd((null as any),0),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_MdbNavComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'mdb-nav',([] as any[]),(null as any),(null as any),(null as any),View_MdbNavComponent_0,RenderType_MdbNavComponent)),
    import1.ɵdid(57344,(null as any),0,import2.MdbNavComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MdbNavComponentNgFactory:import1.ComponentFactory<import2.MdbNavComponent> = import1.ɵccf('mdb-nav',import2.MdbNavComponent,View_MdbNavComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItbmF2L21kYi1uYXYuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWF0ZXJpYWxzLWJjbGlnaHQvbWRiLW5hdi9tZGItbmF2LmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWF0ZXJpYWxzLWJjbGlnaHQvbWRiLW5hdi9tZGItbmF2LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItbmF2L21kYi1uYXYuY29tcG9uZW50LnRzLk1kYk5hdkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XG4gIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbjwvZGl2PlxuPCEtLVRPRE8g0LDQvdC40LzQsNGG0LjRjyDQvdCw0LLQtdC00LXQvdC40Y8tLT5cbiIsIjxtZGItbmF2PjwvbWRiLW5hdj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUs7Z0JBQ0g7SUFBeUI7SUFDckI7SUFDd0I7Ozs7OztJQ0g5QjtnQkFBQTs7O0lBQUE7OzsifQ==
