/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['.card[_ngcontent-%COMP%] {\n  .card-content, .card-action {padding: 0}\n}\n[_nghost-%COMP%]     {\n  mdb-button {padding:0;width:100%;}\n}'];
