/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/main/main.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../../app/main/main-routing.module';
import * as import4 from './main.component.ngfactory';
import * as import5 from '../../../../app/main/main.component';
class MainModuleInjector extends import0.ɵNgModuleInjector<import1.MainModule> {
  _RouterModule_0:import2.RouterModule;
  _MainRoutingModule_1:import3.MainRoutingModule;
  _MainModule_2:import1.MainModule;
  _ROUTES_3:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import4.MainComponentNgFactory],([] as any[]));
  }
  createInternal():import1.MainModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._MainRoutingModule_1 = new import3.MainRoutingModule();
    this._MainModule_2 = new import1.MainModule();
        this._ROUTES_3 = [[{
          path: '',
          component: import5.MainComponent
        }
    ]];
    return this._MainModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.MainRoutingModule)) { return this._MainRoutingModule_1; }
    if ((token === import1.MainModule)) { return this._MainModule_2; }
    if ((token === import2.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory<any>(MainModuleInjector,import1.MainModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9uZ3UtZGVtby9zcmMvYXBwL21haW4vbWFpbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9uZ3UtZGVtby9zcmMvYXBwL21haW4vbWFpbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
