/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/main/main.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../../app/main/main-routing.module';
import * as import4 from '@angular/common';
import * as import5 from '../../../../app/materials-bclight/mdb-nav/mdb-nav.module';
import * as import6 from '../../../../app/materials-bclight/mdb-button/mdb-button.module';
import * as import7 from '../../../../app/materials-bclight/mdb-sidenav/mdb-sidenav.module';
import * as import8 from '../../../../app/materials-bclight/materials-bclight.module';
import * as import9 from '../../../../app/globals/globals.module';
import * as import10 from './main.component.ngfactory';
import * as import11 from '../../../../app/main/main.component';
class MainModuleInjector extends import0.ɵNgModuleInjector<import1.MainModule> {
  _RouterModule_0:import2.RouterModule;
  _MainRoutingModule_1:import3.MainRoutingModule;
  _CommonModule_2:import4.CommonModule;
  _MdbNavModule_3:import5.MdbNavModule;
  _MdbButtonModule_4:import6.MdbButtonModule;
  _MdbSidenavModule_5:import7.MdbSidenavModule;
  _MaterialsBclightModule_6:import8.MaterialsBclightModule;
  _GlobalsModule_7:import9.GlobalsModule;
  _MainModule_8:import1.MainModule;
  _ROUTES_9:any[];
  __NgLocalization_10:import4.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,[import10.MainComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_10():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import4.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_10;
  }
  createInternal():import1.MainModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._MainRoutingModule_1 = new import3.MainRoutingModule();
    this._CommonModule_2 = new import4.CommonModule();
    this._MdbNavModule_3 = new import5.MdbNavModule();
    this._MdbButtonModule_4 = new import6.MdbButtonModule();
    this._MdbSidenavModule_5 = new import7.MdbSidenavModule();
    this._MaterialsBclightModule_6 = new import8.MaterialsBclightModule();
    this._GlobalsModule_7 = new import9.GlobalsModule();
    this._MainModule_8 = new import1.MainModule();
      this._ROUTES_9 = [[
        {
          path: '',
          component: import11.MainComponent
        }
        ,
        {
          path: '#main',
          component: import11.MainComponent
        }

      ]
    ];
    return this._MainModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.MainRoutingModule)) { return this._MainRoutingModule_1; }
    if ((token === import4.CommonModule)) { return this._CommonModule_2; }
    if ((token === import5.MdbNavModule)) { return this._MdbNavModule_3; }
    if ((token === import6.MdbButtonModule)) { return this._MdbButtonModule_4; }
    if ((token === import7.MdbSidenavModule)) { return this._MdbSidenavModule_5; }
    if ((token === import8.MaterialsBclightModule)) { return this._MaterialsBclightModule_6; }
    if ((token === import9.GlobalsModule)) { return this._GlobalsModule_7; }
    if ((token === import1.MainModule)) { return this._MainModule_8; }
    if ((token === import2.ROUTES)) { return this._ROUTES_9; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_10; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory<any>(MainModuleInjector,import1.MainModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL21haW4ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWFpbi9tYWluLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
