/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../modules/transfer-state/browser-transfer-state.module';
import * as import2 from '../../../../modules/transfer-state/transfer-state';
class BrowserTransferStateModuleInjector extends import0.ɵNgModuleInjector<import1.BrowserTransferStateModule> {
  _BrowserTransferStateModule_0:import1.BrowserTransferStateModule;
  __TransferState_1:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _TransferState_1():any {
    if ((this.__TransferState_1 == null)) { (this.__TransferState_1 = import1.getTransferState()); }
    return this.__TransferState_1;
  }
  createInternal():import1.BrowserTransferStateModule {
    this._BrowserTransferStateModule_0 = new import1.BrowserTransferStateModule();
    return this._BrowserTransferStateModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.BrowserTransferStateModule)) { return this._BrowserTransferStateModule_0; }
    if ((token === import2.TransferState)) { return this._TransferState_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BrowserTransferStateModuleNgFactory:import0.NgModuleFactory<import1.BrowserTransferStateModule> = new import0.NgModuleFactory<any>(BrowserTransferStateModuleInjector,import1.BrowserTransferStateModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL21vZHVsZXMvdHJhbnNmZXItc3RhdGUvYnJvd3Nlci10cmFuc2Zlci1zdGF0ZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL21vZHVsZXMvdHJhbnNmZXItc3RhdGUvYnJvd3Nlci10cmFuc2Zlci1zdGF0ZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
