/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['{\n  mdb-button[mdb-icon] {\n    box-shadow: none;\n    span.wave-effect {background:rgba(0, 0, 0, .0);width: 100%;height: 100%;display: block;position: absolute;top: 0;transition: .5s all ease}\n    &:hover {\n      span.wave-effect { background:rgba(0, 0, 0, .1) }\n    }\n    &:active {\n      span.wave-effect { background:rgba(255, 255, 255, .3) }\n    }\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItYnV0dG9uL21kYi1idXR0b24uY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItYnV0dG9uL21kYi1idXR0b24uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
