/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['{\n  mdb-button[mdb-icon] {\n    box-shadow: none;\n    span.wave-effect {background:rgba(0, 0, 0, .0);width: 100%;height: 100%;display: block;position: absolute;top: 0;transition: .5s all ease}\n    &:hover {\n      span.wave-effect { background:rgba(0, 0, 0, .1) }\n    }\n    &:active {\n      span.wave-effect { background:rgba(255, 255, 255, .3) }\n    }\n  }\n}'];
