/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './mdb-button.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../app/materials-bclight/mdb-button/mdb-button.component';
const styles_MdbButtonComponent:any[] = [import0.styles];
export const RenderType_MdbButtonComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MdbButtonComponent,
  data: {}
}
);
export function View_MdbButtonComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵncd((null as any),0),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),0,'span',[[
        'class',
        'wave-effect'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_MdbButtonComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'mdb-button',([] as any[]),(null as any),(null as any),(null as any),View_MdbButtonComponent_0,RenderType_MdbButtonComponent)),
    import1.ɵdid(57344,(null as any),0,import2.MdbButtonComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MdbButtonComponentNgFactory:import1.ComponentFactory<import2.MdbButtonComponent> = import1.ɵccf('mdb-button',import2.MdbButtonComponent,View_MdbButtonComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItYnV0dG9uL21kYi1idXR0b24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWF0ZXJpYWxzLWJjbGlnaHQvbWRiLWJ1dHRvbi9tZGItYnV0dG9uLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L1dvcmsvYW5ndWxhcjItc2VydmVyLXRlc3QvYW5ndWxhcjQtc3NyL3NyYy9hcHAvbWF0ZXJpYWxzLWJjbGlnaHQvbWRiLWJ1dHRvbi9tZGItYnV0dG9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYXRlcmlhbHMtYmNsaWdodC9tZGItYnV0dG9uL21kYi1idXR0b24uY29tcG9uZW50LnRzLk1kYkJ1dHRvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuZy1jb250ZW50PjwvbmctY29udGVudD5cbjxzcGFuIGNsYXNzPVwid2F2ZS1lZmZlY3RcIj48L3NwYW4+XG48IS0tVE9ETyB3YXZlIGVmZmVjdCBidXR0b24tLT5cbiIsIjxtZGItYnV0dG9uPjwvbWRiLWJ1dHRvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnQkNBQTtJQUF5QjtNQUN6QjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlDO0lBQ0g7Ozs7OztJQ0Y5QjtnQkFBQTs7O0lBQUE7OzsifQ==
