/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/+lazy/lazy.module';
import * as import2 from '@angular/router';
class LazyModuleInjector extends import0.ɵNgModuleInjector<import1.LazyModule> {
  _RouterModule_0:import2.RouterModule;
  _LazyModule_1:import1.LazyModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[LazyViewNgFactory],([] as any[]));
  }
  createInternal():import1.LazyModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._LazyModule_1 = new import1.LazyModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import1.LazyView,
          pathMatch: 'full'
        }
    ]];
    return this._LazyModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.LazyModule)) { return this._LazyModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LazyModuleNgFactory:import0.NgModuleFactory<import1.LazyModule> = new import0.NgModuleFactory<any>(LazyModuleInjector,import1.LazyModule);
const styles_LazyView:any[] = ['*[_ngcontent-%COMP%] {color: red}'];
export const RenderType_LazyView:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_LazyView,
  data: {}
}
);
export function View_LazyView_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['i\'m lazy']))
  ]
  ,(null as any),(null as any));
}
function View_LazyView_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'lazy-view',([] as any[]),(null as any),(null as any),(null as any),View_LazyView_0,RenderType_LazyView)),
    import0.ɵdid(24576,(null as any),0,import1.LazyView,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const LazyViewNgFactory:import0.ComponentFactory<import1.LazyView> = import0.ɵccf('lazy-view',import1.LazyView,View_LazyView_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2FuZ3VsYXI0LXNzci9zcmMvYXBwLytsYXp5L2xhenkubW9kdWxlLnRzIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS50cy5MYXp5Vmlldy5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC8rbGF6eS9sYXp5Lm1vZHVsZS50cy5MYXp5Vmlld19Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5pJ20gbGF6eTwvaDM+IiwiPGxhenktdmlldz48L2xhenktdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJOzs7Ozs7SUNBSjtnQkFBQTs7OzsifQ==
