/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['img[_ngcontent-%COMP%] {\n  width: 100%;\n}\n.banners-row[_ngcontent-%COMP%] {\n  margin: {left: -8px; right: -8px};\n  .banner{\n    padding: 8px;\n  }\n  &.banners-top .banner:nth-child(1)  {\n    padding-top: 0;\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9tYWluL2Jhbm5lcnMvYmFubmVycy5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2FuZ3VsYXI0LXNzci9zcmMvYXBwL21haW4vYmFubmVycy9iYW5uZXJzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
