/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['img[_ngcontent-%COMP%] {\n  width: 100%;\n}\n.banners-row[_ngcontent-%COMP%] {\n  margin: {left: -8px; right: -8px};\n  .banner{\n    padding: 8px;\n  }\n  &.banners-top .banner:nth-child(1)  {\n    padding-top: 0;\n  }\n}'];
