/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../app/home/home-view.component';
import * as import3 from '../../../../modules/transfer-http/transfer-http';
const styles_HomeView:any[] = ([] as any[]);
export const RenderType_HomeView:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HomeView,
  data: {}
}
);
export function View_HomeView_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    import0.ɵpid(65536,import1.AsyncPipe,[import0.ChangeDetectorRef])
  ]
  ,(null as any),(ck,v) => {
    var co:import2.HomeView = v.component;
    const currVal_0:any = import0.ɵunv(v,1,0,import0.ɵnov(v,2).transform(co.subs));
    ck(v,1,0,currVal_0);
  });
}
function View_HomeView_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'home-view',([] as any[]),(null as any),(null as any),(null as any),View_HomeView_0,RenderType_HomeView)),
    import0.ɵdid(57344,(null as any),0,import2.HomeView,[import3.TransferHttp],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const HomeViewNgFactory:import0.ComponentFactory<import2.HomeView> = import0.ɵccf('home-view',import2.HomeView,View_HomeView_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9ob21lL2hvbWUtdmlldy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9ob21lL2hvbWUtdmlldy5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Xb3JrL2FuZ3VsYXIyLXNlcnZlci10ZXN0L2FuZ3VsYXI0LXNzci9zcmMvYXBwL2hvbWUvaG9tZS12aWV3LmNvbXBvbmVudC50cy5Ib21lVmlldy5odG1sIiwibmc6Ly8vRDovV29yay9hbmd1bGFyMi1zZXJ2ZXItdGVzdC9hbmd1bGFyNC1zc3Ivc3JjL2FwcC9ob21lL2hvbWUtdmlldy5jb21wb25lbnQudHMuSG9tZVZpZXdfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDM+e3tzdWJzIHwgYXN5bmN9fTwvaDM+IiwiPGhvbWUtdmlldz48L2hvbWUtdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7Z0JBQUE7Ozs7SUFBQTtJQUFBOzs7OztJQ0FKO2dCQUFBOzs7SUFBQTs7OyJ9
